// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ConvertRequest struct {
	LongUrl string `json:"longUrl" validate:"required,http_url"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortUrl"`
}

type ShowRequest struct {
	ShortUrl string `json:"shortUrl" validate:"required,http_url"`
}

type ShowResponse struct {
	LongUrl string `json:"longUrl"`
}
